### ISSUE TITLE
Batch edit metadata for a field

### ISSUE THREAD

**Issue by transat** [MukurtuCMS/mukurtucms#10]
Is there a way to batch edit a field's metadata over a number of DH items?

**Comment by steve-taylor-wsu** [comment]
Not currently for fields that aren't linked to taxonomies.

The next release should have the new export/import functionality that would let you export some items, edit the metadata in the CSV, then re-import to update them.

Is this the sort of thing you are thinking about?

**Comment by transat** [comment]
I was thinking about a way of doing that internally. Here's how it might work:

1) I access a searchable list of DH items and select the ones I'd like to edit (either manually or optionally by clicking on "select all")
2) I'm asked to select a field amongst all the available ones.
3) I enter in the new/amended data.
4) I'm asked to choose whether this data should be added to or replace the current contents of the field.
5) I get the option of repeating steps 2-4 with another field.
6a) [Optional] I'm shown a preview of what the edited fields will look like
6b) I click on "Batch Edit" and voila!

As this is an enhancement/feature request. Please feel free to close this issue.

Cheers!

**Comment by steve-taylor-wsu** [comment]
Thanks for the description.  I think that would be good addition and possible.  I'll add it to the requested features.
