### ISSUE TITLE
Question: How might I change the page template for the dictionary page?

### ISSUE THREAD

**Issue by KelleyCoda** [MukurtuCMS/mukurtucms#101]
A client would like to replace the title on /dictionary to say "wordlist" instead. 

I tried creating page--dictionary_browse.tpl.php with the different title, but it's not overriding the page.

Is there a preprocess hook I need to add somewhere? If so, where would I add it?

Thanks!

**Comment by steve-taylor-wsu** [comment]
That page is a panel:

/admin/structure/pages/edit/page-dictionary_browse

Go to "Content" then you can edit the title there.

**Comment by KelleyCoda** [comment]
Thanks Steve, I have a couple issues when I try to do that.

a: The title override won't save. This happens for the dictionary panel only and its consistent across every Mukurtu site I tried. 
![image](https://cloud.githubusercontent.com/assets/5231994/24730103/8ae29ab6-1a16-11e7-8c7d-5b5f0ecf6e63.png)

b: I would like to make the override in my theme folder if possible so that I don't have to manage feature revisions after every upgrade.

**Comment by steve-taylor-wsu** [comment]
Indeed. If you are the position to test this, try overwriting the file:

sites/all/modules/custom/features/ma_dictionary/ma_dictionary.pages_default.inc

With the same file from the 143215233-error_saving_changes_to_dictionary_panel branch.

If you can't change files, try changing the menu to something else (like "Normal menu entry"), Update and Save, then change it back to "No menu entry". Then try making your title change.

As far as upgrades, this sort of change would need to be captured by [Features Override](https://github.com/MukurtuCMS/mukurtucms/wiki/Using-Features-Override-to-Capture-Local-Site-Customization). It is our goal to make this easier to change via a theme, but we aren't quite there yet.

Thanks.

**Comment by KelleyCoda** [comment]
Thanks Steve! 143215233-error_saving_changes_to_dictionary_panel helped out!
