### ISSUE TITLE
colorbox installed incorrectly

### ISSUE THREAD

**Issue by edsu** [MukurtuCMS/mukurtucms#113]
I don't know if it is significant or not (hi, new user) but when I set up mukurtu I noticed on my status report page /admin/reports/status that the colorbox plugin wasn't installed correctly. I took a look on the server and a colorbox directory is embedded inside the colorbox directory at `sites/all/libraries/colorbox/colorbox`. It is this way in the gitjub repo as well. I downloaded the latest colorbox plugin and moved it into place at `sites/all/libraries/colorbox` and the warning went away.

**Comment by steve-taylor-wsu** [comment]
It is indeed a bug and not insignificant. We've had it fixed in the develop branch for a while, but haven't yet moved the fix to master. A new release should be coming in the next few weeks that will include the updated colorbox library in the correct location. Thanks for the report!
