### ISSUE TITLE
Options for updates

### ISSUE THREAD

**Issue by kingsnafu** [MukurtuCMS/mukurtucms#117]
Would like to see some options for updating Mukurtu. We get drush errors and they are hard to troubleshoot and fix, and are a burden to our organization. The last few updates I just went to /update.php in the browser to complete the updates. 

Would also like to see instructions on how to export all content from Mukurtu and import into a new install. That way when there are drush errors I can create a new Mukurtu install and import the data. This would give us peace of mind that we are running a clean latest version.

I found some export/import instructions online but they seem outdated and does not apply to our use case.

**Comment by steve-taylor-wsu** [comment]
What kind of drush errors are you getting and during which steps? Drush is fairly verbose, almost all of the notices/warnings can safely be ignored. During the database update step, drush and update.php are using the exact same backend, so whichever you prefer will work. If you are upgrading multiple version numbers (e.g., 2.0.8 to 2.1.1) it is common to have some warnings/errors, you may need to run the database update and feature revert steps multiple times to resolve all dependency issues.

I would not recommend trying to use the import/export functionality as routine method of site migration. There are many things stored in the database (site configuration, user data, comments, etc) that are not covered by the exporter and in general migrating a site via import/export is a very labor intensive process that takes significant planning and validation.

However if you want to keep your existing database and start with fresh Mukurtu files, that is fairly easy and any standard Drupal migration plan should work. In general terms you would:

- Backup your site (`drush archive-backup`)
- Clone your database (or use the existing if you aren't keeping the old site around)
- Checkout the fresh copy of Mukurtu to a new location
- Copy your site files over from the old folder to the new folder (usually 'sites/default/files')
- Update settings.php in the new location with your database configuration details
- Change your web server configuration to reflect the new location

**Comment by kingsnafu** [comment]
Thank a lot for the information. The drush errors are definitely not warnings and the fact that I can finish the update using update.php confirms that. I think that will be our course of action from now on, just update the files and then run update.php from the browser. Thanks again.
