### ISSUE TITLE
"Drupal already installed"

### ISSUE THREAD

**Issue by chobeat** [MukurtuCMS/mukurtucms#120]
I'm trying to install Mukurtu in a dockerized environment and I get this error after passing the check and permissions step in the wizard. I followed the guide and modified `settings.php`, filling it with the info for the database and I stop at the `Drupal already installed` error. I also tried to set the `base_url` but it doesn't help. I think the `$GLOBALS['databases']` is empty and so this exception is raised: https://github.com/chobeat/mukurtucms/blob/master/includes/install.core.inc#L1362

How can I debug this? I've found some comments on the internet but they are all pretty old and none seem to be fixing the problem. Is there some other place where `databases` is getting overriden? Am I doing something wrong? Also in Drupal 7 the database is usually configured through the wizard, why isn't the same for mukurtu?

**Comment by chobeat** [comment]
Removing the whole `databases` entry from the `settings.php` let's me proceed with the wizard. I suggest somebody reviews the guide and the default.settings.php because it seems what you suggest to do conflicts with what Drupal is expecting.

**Comment by steve-taylor-wsu** [comment]
Hello. 

Glad you got it figured out. I agree that the documentation could use refreshing. We recommend pre-filling settings.php for most users because at the time it side-stepped some common issues with the Drupal 7 installation wizard, on some platforms. Today I think this is less of a concern. Thanks.

**Comment by ericnitschke** [comment]
@chobeat @steve-taylor-wsu Thanks for the great work. Any plans for a docker update? Is [this](https://hub.docker.com/r/cbenning/mukurtucms) the most recent around? Would love to include this in [Lokal](https://wakoma.co/lokal/). Thanks.

**Comment by steve-taylor-wsu** [comment]
Hello. Mukurtu v3 is receiving security updates only as we put all our development efforts into the Drupal 9 version. Other than the included Lando file, it's unlikely we'll do anything with Docker for v3. Thanks.

**Comment by ericnitschke** [comment]
Thanks, @steve-taylor-wsu.  Docker of Drupal 9 version perhaps?
