### ISSUE TITLE
Export DHI's error based on category(?)

### ISSUE THREAD

**Issue by HeleneJulienne** [MukurtuCMS/mukurtucms#121]
I am getting the following error message when trying to export one of my Mukurtu categories for a roundtrip edit:

Error message
An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: /batch?id=476&op=do StatusText: error ResponseText:
An error occurred while processing views_bulk_operations_active_queue_process with arguments: views_bulk_operations_active_queue_process

I tested and it seems to only be occurring with this particular category and I'm still able to export individual DHI's within this category. I'm managing content for this Mukurtu project but have zero programming experience. Can someone help?

**Comment by steve-taylor-wsu** [comment]
Could you test the failing scenario again, then check the logs at "Reports -> Recent Log Messages". Then filter by severity "error" and share any errors that correspond to your testing time? The AJAX error you posted above is more of a generic catch all, I'm hoping there is more detailed information in the system logs. Thanks!

**Comment by HeleneJulienne** [comment]
![Screen Shot 2019-07-26 at 1 48 13 PM](https://user-images.githubusercontent.com/53352816/61980595-0b47c780-afac-11e9-95f0-2f63e1f0f69a.png)

**Comment by HeleneJulienne** [comment]
Thanks! this is the message. Screenshot attached above:

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '768-1-733' for key 'PRIMARY': INSERT INTO {community_tags} (tid, nid, uid, date) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3); Array ( [:db_insert_placeholder_0] => 768 [:db_insert_placeholder_1] => 733 [:db_insert_placeholder_2] => 1 [:db_insert_placeholder_3] => 1564173984 ) in _community_tags_add_tag() (line 1033 of /home/nuuchahn/public_html/sites/all/modules/contrib/community_tags/community_tags.module).

**Comment by steve-taylor-wsu** [comment]
Interesting! If you are on Mukurtu 2.1 or higher, I'd recommend turning off the community tags module and trying again. You'd do that by:

* Clicking "Modules" in the site admin bar (or site name + /admin/modules)
* Type "tags" in the filter list
* Switch "Community Tags" to off and click "Save configuration"

Then I'd try the export operation again. Thanks.

**Comment by HeleneJulienne** [comment]
Great, the export worked after turning off Community Tags. I had recently done a "clean up" of our keywords and deleted several of them so perhaps it is related.

**Comment by steve-taylor-wsu** [comment]
Great, I'm glad it is working now.
