### ISSUE TITLE
Files directory patch does not play well with symbolic links

### ISSUE THREAD

**Issue by rtrvrtg** [MukurtuCMS/mukurtucms#124]
Tricky developer experience issue here... The patch in `patches/core/ignore_files_dir_contents_but_include_files_dir_itself.patch` really doesn't play well with files directories that have been set up as symbolically linked. While this doesn't result in data loss since it's just a symlink, it can result in moments of panic as the files all just disappear.

In my local instance I'm going to comment out that patch in the makefile so it doesn't inadvertently cause any trouble, but I was wondering if anyone who uses Mukurtu in a similar fashion might have any advice.

**Comment by shirazd** [comment]
Hi there. I wrote that patch simply to simplify the install for sys admins. You can exclude that patch without issue.

**Comment by rtrvrtg** [comment]
Goodoh, thanks for the background.
