### ISSUE TITLE
Errors in attempting to upload media

### ISSUE THREAD

**Issue by gloriousgeneralist** [MukurtuCMS/mukurtucms#153]
I've been attempting to upload media items to the SCALD library, and keep getting file limit errors in the browser, though have verified that PHP and the configurations are set to allow files of that size. I've checked the logs and getting some errors that suggest to me that there's some sort of other PHP error. We were running Mukurtu on a different server prior to this with a different Linux distribution and didn't see errors like this, so curious if anyone has seen these before and knows potential causes. Here are a few of the errors I get in the log:

Notice: Trying to access array offset on value of type null in mukurtu_protocol_field_form_alter() (line 63 of /var/www/html/mukurtucms/sites/all/modules/custom/mukurtu_protocol_field/mukurtu_protocol_field.module).

Warning: A non-numeric value encountered in argfilters_views_query_substitutions() (line 22 of /var/www/html/mukurtucms/sites/all/modules/contrib/argfilters/argfilters.module).

Warning: Invalid argument supplied for foreach() in mukurtu_protocol_field_form_alter() (line 63 of /var/www/html/mukurtucms/sites/all/modules/custom/mukurtu_protocol_field/mukurtu_protocol_field.module).

Notice: Undefined property: stdClass::$og_group_ref in mukurtu_protocol_field_form_alter() (line 63 of /var/www/html/mukurtucms/sites/all/modules/custom/mukurtu_protocol_field/mukurtu_protocol_field.module).

**Comment by steve-taylor-wsu** [comment]
I'd recommend confirming that both `post_max_size` and `upload_max_filesize` were increased sufficiently and that those increased values are reflected in phpinfo on the website itself (/devel/phpinfo as an admin).

Those PHP messages are notices/warnings, not errors, so those particular messages wouldn't be likely causes of this issue. Mukurtu CMS v3 is quite noisy in terms of PHP warnings/notices so there might be errors buried in there somewhere. There's an option to filter by error, might be worth checking if there are any at the time of upload. However if you're getting file limit messages, that suggest to me it's likely a system config issue. A PHP error would more often result in a crash or a generic error message.

**Comment by gloriousgeneralist** [comment]
Thanks @steve-taylor-wsu, it looks like post_max_size wasn't set, only upload_max_filesize!
