### ISSUE TITLE
PHP message: PHP Deprecated:  Creation of dynamic property MemCacheDrupal::$bin is deprecated

### ISSUE THREAD

**Issue by cpunj** [MukurtuCMS/mukurtucms#163]
Hi team,

I recently started having an issue with Memcache module in our installation of Mukurtu. We have been running Mukurtu using PHP 8.3.2-1+ubuntu20.04.1+deb.sury.org+1 for a while now but suddenly for some reason, it has started acting weird on us. Facet APIs for dynamic filtering and search keep appearing and disappearing when the cache is cleared. Once they appear after the cache and you select any of the filters, they disappear again. I tried reverting to the PHP 7.4 again but that did not solve the issue. Neither did reinstalling the Memcache module work. Can you please suggest what can be the fix here?

Regards,
cpunj
<img width="1387" alt="Before cache is cleared" src="https://github.com/MukurtuCMS/mukurtucms/assets/64109470/5e6502f7-412a-4890-bea5-f3d41f81d4e8">
<img width="2537" alt="After cache is cleared" src="https://github.com/MukurtuCMS/mukurtucms/assets/64109470/790bf711-d556-4bab-a710-23fdf9ff3a8e">

<img width="1579" alt="error" src="https://github.com/MukurtuCMS/mukurtucms/assets/64109470/730c32a8-e6de-4568-91ad-7a7e1ad618b2">

**Comment by alexmerrill** [comment]
Hello -

I don't have a lot of experience with Memcache and Mukurtu/Drupal myself.  We can do a little investigation and see if we have any ideas. What version of the Drupal Memcache Module are you using?  Does your site work as expected without the Memcache module present?

Thanks --
AM

**Comment by cpunj** [comment]
Hi Alex,

Thanks for responding. The site works when I disabled the memcache module but the caching issue still exists. I believe it is -memcached 1.5.22 which shows up when I type the command 'memcached -h". 

Thank you

Kind regards,
cpunj
