### ISSUE TITLE
Batch import failed due to unicode character

### ISSUE THREAD

**Issue by transat** [MukurtuCMS/mukurtucms#17]
A batch of DH items I've just ingested has failed and the record it failed on included an accented character. (e.g., "Mrs. Smith, **née** Williams") which makes me think that is the reason? It's easy enough for me to skip the accented e here but due to the large quantity of language material we will be importing, this could potentially be an issue (linguists use diacritics extensively).

**Comment by transat** [comment]
Confirming that it the problem is due to the accented character. The error message I received is: `SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xE9e Mor...' for column 'name' at row 1` but from what I've read I can avoid this by opening up the csv file in a suitable text processor and converting it to UTF8 encoding. Any chance the conversion can happen upon import instead?

**Comment by shirazd** [comment]
right, the php function utf8_encode function should be used during the import. are you open to doing this yourself? i didn't code the import myself but i can say you should find where you'd do this relatively easily. i'll merge it in following your change.

**Comment by transat** [comment]
Unfortunately I have no PHP coding experience. If there's an easy solution available online - I've found a couple of leads so far - I'll give it a try otherwise I'll see if anyone in our IT department is able to do this once we have a dev environment set up. Looks the fix could either involve a patch to Feeds (the latest version might actually already have this) or a plugin for Feeds Tamper. Thanks again for all your help.

**Comment by transat** [comment]
Potentially solved by the last patch here: https://www.drupal.org/node/1428272 but I'm unable to apply it and test it at this stage.

**Comment by steve-taylor-wsu** [comment]
They haven't rolled that into the dev branch of feeds yet.  I tried it locally and at first glance it seems to work.  I've attached the whole module if you want to try it on your local instance.  We'll need to do some testing before rolling it in.  Thanks.
[feeds_with_patch.zip](https://github.com/MukurtuCMS/mukurtucms/files/89686/feeds_with_patch.zip)

**Comment by transat** [comment]
Cheers! I should be able to test it by the end of next week. I'll let you know how we go.

**Comment by steve-taylor-wsu** [comment]
Version 2.0.4 is now using a version of Feeds that allows you to select your file encoding on import.
