### ISSUE TITLE
URLs included in a collection description do not open in a new tab.

### ISSUE THREAD

**Issue by transat** [MukurtuCMS/mukurtucms#18]
URLs are automatically formatted as links but these links do not contain a `target="_blank"` attribute, which may lead to users being steered away from the collection.

**Comment by shirazd** [comment]
It would be better to word this as a feature request than a bug. Current behaviour was as intended. Though I see your point...

**Comment by lifeisnotstill** [comment]
Agreed. I think gathering some user feedback is in order. I'm a _fan_ of tabs, but we need consider mobile experience, and proliferation of tabs or pages.

**Comment by transat** [comment]
Apologies. I don't think I have access to issues 'labels' to specify that this was a feature request more so than a bug. I'm happy to send any such request by email instead if there is a preferred contact.

**Comment by transat** [comment]
Potentially solved by the last patch here: https://www.drupal.org/node/1428272 but I'm unable to apply it and test it at this stage.
