### ISSUE TITLE
iOS Rotation in SCALD

### ISSUE THREAD

**Issue by KelleyCoda** [MukurtuCMS/mukurtucms#25]
When I upload an iOS photo it doesn't interpret the rotation value of the image.

This may solve, but maybe not for SCALD:
https://www.drupal.org/project/exif_orientation
"This module reads EXIF data to rotate images that have an Orientation key set. This module solves the issue where iOS devices take images in one position but set an EXIF Orientation value, leaving applications viewing the image responsible for rotating the image."

**Comment by steve-taylor-wsu** [comment]
In develop we are now running an auto-rotate image effect for most of the image styles.  Thumbnails, DH image preview, etc should now rotate based on the EXIF orientation metadata.  The original image will remain unmodified, so when clicking through to the "access image" the rotation will be dependent on the user's browser/viewer. This should make it into 2.0.5, unless problems arise.  Thanks.

**Comment by steve-taylor-wsu** [comment]
Included in 2.0.5.
