### ISSUE TITLE
As a Mukurtu Administrator, I would like to be able to manage 'people' and other taxonomies

### ISSUE THREAD

**Issue by KelleyCoda** [MukurtuCMS/mukurtucms#32]
Just like I can manage keywords and categories, I would like to be able to manage the "people" taxonomy among others.

Submitted to CoDA by Adrienne Harling, Administrator and Sipnuuk Archives Manager.

**Comment by steve-taylor-wsu** [comment]
This has been fixed in develop and will be included in the 2.0.5 release.  Thanks.

**Comment by annieneuner** [comment]
I would like it if the parent nodes could be sorted alphabetically, right now we're having to drag and drop each new parent node into alphabetical order and as the list grows that could become super annoying.

**Comment by annieneuner** [comment]
I can't drag and drop to the next page, making it impossible to sort the parent nodes correctly.
