### ISSUE TITLE
Hook up Soundcloud to SCALD

### ISSUE THREAD

**Issue by KelleyCoda** [MukurtuCMS/mukurtucms#40]
Requested by Te Reo o Taranaki: As a(n) Contributor When I am Adding Audio / Media I would like To be able to add from Soundcloud so that  I can have representations from a publishing service I already use.
- Once soundcloud is accepted by SCALD audio within the site, I would also expect that a soundcloud URL I add to the Digital Heritage Metadata Importer or the Audio importer would perform the same task.

**Comment by steve-taylor-wsu** [comment]
We have Soundcloud support included in develop currently, to be included in the next release.

The Digital Heritage Metadata importer will take a Soundcloud URL and will automatically pull in the author and tags that Soundcloud returns for that atom.

The Media: Audio importer will take a Soundcloud URL but will not do anything automatically with the author and tags, instead only using the information specified in the input file.

On export, the Soundcloud "media" will be the Soundcloud URL.

**Comment by steve-taylor-wsu** [comment]
This has been included in 2.0.7.

**Comment by KelleyCoda** [comment]
Hooray!

--

Kelley Shanahan
Technical Lead & Experience Designer



*We care for people, their stories, and our diverse cultures and traditions*


*Center for Digital Archaeology*
kelley@codifi.org
centerfordigitalarchaeology.org
