### ISSUE TITLE
CSV semicolon glitch

### ISSUE THREAD

**Issue by transat** [MukurtuCMS/mukurtucms#6]
Upon importing a batch with multiple subjects separated by semicolons, the DH items appear to combine those subjects into one, ignoring the semicolon. Clicking on 'edit' and then 'save' seems to correctly split the subjects based on the semicolons.

**Comment by steve-taylor-wsu** [comment]
Greetings.

Currently we use commas as the multi-value delimiter during import (we do use semicolons as as the delimiter in the web interface).  We may change this in the future to be consistent, but for the moment you could change your instance by overriding the tamper settings for "explode" in the importer (admin/structure/feeds/digital_heritage_metadata/tamper/).

**Comment by transat** [comment]
Aha. It seems this relates to [issue #7](https://github.com/MukurtuCMS/mukurtucms/issues/7) which you've addressed as well. We'll override the tamper settings in the meantime. Thanks for the prompt reply. I'll close this issue as #7 should fix the problem.
