### ISSUE TITLE
customize-tk is now a link on menu, dropped down from dashboard

### ISSUE THREAD

**Issue by KelleyCoda** [MukurtuCMS/mukurtucms#65]
After 2.0.4 updates, when I'm on the dashboard, the dashboard button itself is a dropdown menu for customizing TK labels. When I'm on the TK customization page, I cant get back to the dashboard.

**Comment by alexmerrill** [comment]
Confirmed for inclusion in 2.0.5  just FYI, there is a working link for the dashboard in the breadcrumb on the customizing TK labels page (not prominent -- but it is there).

**Comment by steve-taylor-wsu** [comment]
One item was missing a 'MENU_CALLBACK' flag. Workaround is to go to '/admin/structure/menu/manage/main-menu' and disable 'Customize Site-Wide Traditional Knowledge Label Text'.

**Comment by steve-taylor-wsu** [comment]
This has been fixed in 2.0.5. Thanks.
