### ISSUE TITLE
Export DH: when downloading records with related Items, download never happens.

### ISSUE THREAD

**Issue by KelleyCoda** [MukurtuCMS/mukurtucms#67]
I chose 35 items to export with the complete zipped file, but it didn't download onto my computer. I did get a success notice in the CMS. It had a download link, but the download link did nothing.

I managed to replicate this bug. It turns out, if I select "related items" in the fields to export, it doesn't give you a download. It shows the button, but it does nothing when you press it. This is regardless of ZIP or CSV export.

**Comment by alexmerrill** [comment]
Interesting,  I can export the NIDS for the Related Items on a few of our sites (in both .CSV and .ZIp).  I am aware of the bug where the URL to download the .zip fails.  Are there any other factors you can think of on this one?

**Comment by KelleyCoda** [comment]
Hmm. I'm not able to replicate this now. Let's close this one and I'll keep an eye out for it in the future...
