### ISSUE TITLE
CSV separator inconsitencies

### ISSUE THREAD

**Issue by transat** [MukurtuCMS/mukurtucms#7]
Unless I'm doing something wrong... In the CSV file needed for batch imports, some fields which accept multiple values require those values to be split by commas (the 'keyword' field) while others require semicolons (the 'subject' field). This is confusing.

**Comment by steve-taylor-wsu** [comment]
You are not doing anything wrong, you have found a bug.  It appears we lost/never attached the feeds tamper plugins for the subject field.  I've added a ticket to our bug tracker and we will fix it for the next release.  Until then, a workaround would be to add the "explode" plugin to the subject field via admin/structure/feeds/digital_heritage_metadata/tamper/.  Thanks!

**Comment by transat** [comment]
Thanks for the quick reply. We'll try your suggestion as a workaround.

**Comment by steve-taylor-wsu** [comment]
In 2.0.4 we've switched all the delimiters to use the semi-colon character.  This should hopefully make everything consistent now.
