### ISSUE TITLE
Roundtrip: Zip File is not Current

### ISSUE THREAD

**Issue by KelleyCoda** [MukurtuCMS/mukurtucms#70]
The sample zip file on the Import batch content page links to a Mukurtu 1.5 sample zip. The Templates and information need to be changed.

**Comment by steve-taylor-wsu** [comment]
We've put a new, very simple sample zip file in the 2.0.5 release. Ideally we'll revisit this and populate it with an entire sample site, but for this release we didn't quite have the time. Thanks.
