### ISSUE TITLE
Allow contributors to delete SCALD atoms

### ISSUE THREAD

**Issue by KelleyCoda** [MukurtuCMS/mukurtucms#75]
As a community administrator, I just uploaded an image to the site. While I was able to go back and edit the SCALD atom, I was not able to delete the atom.

As a contributor, if I create an atom, I would like to be able to come back and delete the atom later.

**Comment by steve-taylor-wsu** [comment]
In for 2.0.7:

* The creator of an atom should be able to delete their own atom, provided it is not being actively referenced by other content (DH, DW, taxonomy term, etc)
* Mukurtu Admins/Administrators can delete any atoms, provided they are not being actively referenced by other content
