### ISSUE TITLE
Mukurtu Admin does not have access to Community Records importer

### ISSUE THREAD

**Issue by KelleyCoda** [MukurtuCMS/mukurtucms#76]
As a mukurtu admin user, I would like to be able to import community records. There is no importer available for this role at the moment. See screenshots of dashboard and /import, logged in as Mukurtu Administrator role.

![image](https://cloud.githubusercontent.com/assets/5231994/18015901/834c3f9c-6b7e-11e6-8e73-d2330362b802.png)

![image](https://cloud.githubusercontent.com/assets/5231994/18015948/c375c098-6b7e-11e6-8039-53d3a7c8951b.png)

**Comment by steve-taylor-wsu** [comment]
Fixed for 2.0.7. Mukurtu Admins should now have access to importers for content types they can create.
