### ISSUE TITLE
Location Description field in CSV not importing

### ISSUE THREAD

**Issue by transat** [MukurtuCMS/mukurtucms#8]
Whatever I type in the "Location Description" field in a CSV bacth import, appears to be ignored.

**Comment by steve-taylor-wsu** [comment]
Are you running off the master branch release and are you up-to-date?  I just tried a simple test and it worked on my test instance running the current release.  Would you be willing to provide me an example file so I can try to replicate (you can email steve_taylor@wsu.edu if you don't want to attach it here)?  Thanks!

**Comment by transat** [comment]
I believe we're still on Mukurtu 2.02. I'm using a slightly customised template spreadsheet for the import so may well have introduced an error somewhere. Here is the draft template I'm using. Please note that input goes into the second sheet which then generates sheet 1 which gets exported as the CSV. 

[BatchTemplate.xlsx](https://github.com/MukurtuCMS/mukurtucms/files/58841/BatchTemplate.xlsx)

Let me know if you'd prefer a version of the spreadsheet with real data and I can email that to you.

Cheers,

Clem.

**Comment by steve-taylor-wsu** [comment]
That spreadsheet is missing the Excel formula to copy over the location description cell from the InputData sheet to your batch sheet.  Could you check if that is a problem?  Thanks!

**Comment by transat** [comment]
Whoops! Cheers.
