### ISSUE TITLE
When unblocking users via "update options", their OG memberships disappear

### ISSUE THREAD

**Issue by KelleyCoda** [MukurtuCMS/mukurtucms#82]
I tested user self-registration.

I found that when an admin approves (aka unblocks) a user by clicking the checkbox on "/admin/people" and selecting "unblock the selected users" under update options:

1. any community they marked while creating their account disappears from their profile.
2. any protocol/community which would automatically register new users to the group also disappears from their profile.

Instead, the admin must edit the user's profile and select "unblock" to preserve OG roles.

**Comment by steve-taylor-wsu** [comment]
I believe this was the same root issue as https://github.com/MukurtuCMS/mukurtucms/issues/85 and the fix will be included in 2.0.7. Thanks!

**Comment by steve-taylor-wsu** [comment]
Fixed in 2.0.7
