### ISSUE TITLE
Dictionary Importer Issues

### ISSUE THREAD

**Issue by KelleyCoda** [MukurtuCMS/mukurtucms#84]
Skips part of speech. Do I need to create the terms ahead of time?

Enters the Pronunciation as blank, so that the field label shows on imported words, even when empty.

Wordlist. Items are indexed to wordlists, but don't appear on the wordlist page when I click on the wordlist title from a dictionary item.

**Comment by steve-taylor-wsu** [comment]
Parts of Speech now auto-create when importing in 2.0.7.

Blank dictionary fields resulting from import is fixed.

The wordlist issue should be fixed as well, please re-open if you find this is still a problem.
