### ISSUE TITLE
Mukurtu Admin OG permissions stripped unexpectedly

### ISSUE THREAD

**Issue by EdibleArchaeologist** [MukurtuCMS/mukurtucms#85]
Noticed in version 2.0.6 & replicated in two different instances.

1.  I'm logged in as Mukurtu Admin
2. I edit a digital heritage item
3. I click "hide wizard" at top of the page

The page reloads.... I get access denied. Weird. 

I go to my account & realize I have NO access to communities and protocols I was previously a member of.

Tested with "Community Admin" & "Admin" roles, but appears to only be affecting the "Mukurtu Admin" role.

**Comment by KelleyCoda** [comment]
ps: That's from me. I was accidentally logged in from a personal account!

**Comment by steve-taylor-wsu** [comment]
Hi Kelley,

Thanks for reporting this. I was able to replicate the issue and pushed an initial fix to develop now. I need to add some additional test cases to our test suite, but the fix will be included in the next release either as is or with additional tweaks. Thanks.

**Comment by steve-taylor-wsu** [comment]
Fixed in 2.0.7.

**Comment by lbhc-jane** [comment]
I am having the same issues, I have called and emailed everyone, everything no replys from ANYONE!  lbhc-Mukurtu.org
