### ISSUE TITLE
Creator field glitch in CSV batch

### ISSUE THREAD

**Issue by transat** [MukurtuCMS/mukurtucms#9]
If I enter `Hemingway, E` under the creator field in the CSV batch file, the DH item then appears to show two creators: `Hemingway` and `E`.

**Comment by steve-taylor-wsu** [comment]
We just ran into this the other day.  Until we make the importer slight more sophisticated, I'd recommend changed the explode plugin to something else.  I used '||'.  You'd change the string separator at admin/structure/feeds/digital_heritage_metadata/tamper/digital_heritage_metadata-creator-explode/edit to "||" then you could have things like "Hemingway, E||Hemingway, F" in your creator column in the CSV file.  It doesn't need to be '||', you could use just about anything for the separator.  Thanks!

**Comment by transat** [comment]
No worries and thank you. Looking forward to the new importer.

**Comment by transat** [comment]
I've changed all the delimiters in the explode plugins to semicolons and it works fine now.

**Comment by transat** [comment]
Changing all the separators to semicolons has worked well.

**Comment by steve-taylor-wsu** [comment]
With the switch to semi-colon delimiters in 2.0.4, commas will work now.
